shops/deed/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('add/', views.person_create_view, name='person_add'),
    path('add2/', views.person_create_view2, name='person_add2'),

    path('', views.select_deed, name='select-deed'),
    path('sales/', views.sales_deed, name='sales-deed'),
    path('gift/', views.gift_deed, name='gift-deed'),
    path('purchase/', views.purchase_deed, name='purchase-deed'),

    # path('deed_edit_download/', views.deed_edit_download, name='edit-download-deed'),

    path('download_form_sales/<str:unique_id>/', views.download_form_sales, name='form-download-sales'),
    path('download_form_gift/<str:unique_id>/', views.download_form_gift, name='form-download-gift'),
    path('download_form_purchase/<str:unique_id>/', views.download_form_purchase, name='form-download-purchase'),

    # Ajax
    path('ajax/load-fwn/', views.load_fwm, name='ajax-fwm-url'),  # AJAX
    path('ajax/load-fwn2/', views.load_fwm2, name='ajax-fwm-url2'),  # AJAX
    path('ajax/load-gift/', views.load_gift, name='ajax-fwm-gift'),  # AJAX
    path('ajax/load-gift2/', views.load_gift2, name='ajax-fwm-gift2'),  # AJAX

    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
    path('ajax/load-income/', views.load_income, name='ajax_load_income'),  # AJAX
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shops/shops/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('deed/', include('deed.urls')),
    path('', include('nearbyshops.urls')),

]

shops/deed/models.py
from django.db import models


class Gender(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Position(models.Model):
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    earning = models.CharField(max_length=3, default='NO')
    name = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.gender} {self.name}'


class Person(models.Model):
    name = models.CharField(max_length=124)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, blank=True, null=True)
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, blank=True, null=True)
    married = models.BooleanField(default=False)
    income = models.FloatField()
    birth_date = models.DateField()

    def __str__(self):
        return self.name


class FMW(models.Model):
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name}:'


REPRESENTY_CHOICES =(
    ("Agent", "Agent"),
    ("Father", "Father"),
    ("Mother", "Mother"),
    ("Brother", "Brother"),
    ("Guardian", "Guardian"),
)


class SalesDeed(models.Model):
    name = models.CharField(max_length=200)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, blank=True, null=True)
    married = models.BooleanField(default=False)
    fwm = models.ForeignKey(FMW, on_delete=models.SET_NULL, blank=True, null=True)
    fwm_name = models.CharField(max_length=150)
    birth_date = models.DateField()
    occupation = models.CharField(max_length=150)
    address = models.TextField()
    seller = models.BooleanField(default=True)
    representy = models.CharField(choices=REPRESENTY_CHOICES, max_length=8)
    unique_id = models.CharField(max_length=150, unique=True)
    
    def __str__(self):
        return self.name


class SalesDeedRepresentative(models.Model):
    representative_name = models.CharField(max_length=200)
    representative_gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, blank=True, null=True)
    representative_married = models.BooleanField(default=False)
    representative_fwm = models.ForeignKey(FMW, on_delete=models.SET_NULL, blank=True, null=True)
    representative_fwm_name = models.CharField(max_length=150)
    representative_birth_date = models.DateField()
    representative_occupation = models.CharField(max_length=150)
    representative_address = models.TextField()
    representative_seller = models.BooleanField(default=False)
    representative_unique_id = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.representative_name


class GiftDeed(models.Model):
    name = models.CharField(max_length=200)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, blank=True, null=True)
    married = models.BooleanField(default=False)
    fwm = models.ForeignKey(FMW, on_delete=models.SET_NULL, blank=True, null=True)
    fwm_name = models.CharField(max_length=150)
    birth_date = models.DateField()
    occupation = models.CharField(max_length=150)
    address = models.TextField()
    unique_id = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class GiftDonorDeed(models.Model):
    representative_name = models.CharField(max_length=200)
    representative_gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, blank=True, null=True)
    representative_married = models.BooleanField(default=False)
    representative_fwm = models.ForeignKey(FMW, on_delete=models.SET_NULL, blank=True, null=True)
    representative_fwm_name = models.CharField(max_length=150)
    representative_birth_date = models.DateField()
    representative_occupation = models.CharField(max_length=150)
    representative_address = models.TextField()
    representative_unique_id = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.representative_name


class PurchaseDeed(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()
    place = models.CharField(max_length=200)
    seller_name = models.CharField(max_length=200)
    seller_address = models.TextField()
    unique_id = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Deed(models.Model):
    name = models.CharField(max_length=200)
    deed = models.TextField()

    def __str__(self):
        return self.name

shops/deed/views.py
from django.shortcuts import render, redirect, get_object_or_404
from uuid import uuid4
from datetime import datetime

from .forms import PersonCreationForm, SalesDeedForm, SalesDeedRepresentativeForm, GiftDeedForm, GiftDonorDeedForm, \
                   PurchaseDeedForm, DeedEditDownloadForm
from .models import Person, Position, SalesDeed, FMW, SalesDeedRepresentative, GiftDeed, GiftDonorDeed, PurchaseDeed

from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa


class Render:
    @staticmethod
    def render(path: str, params: dict):
        template = get_template('deed/sales_deed_download_form.html')
        html = template.render(params)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            return HttpResponse(response.getvalue(), content_type='application/pdf')
        else:
            return HttpResponse("Error Rendering PDF", status=400)


class Render1:
    @staticmethod
    def render(path: str, params: dict):
        template = get_template('deed/gift_deed_download_form.html')
        html = template.render(params)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            return HttpResponse(response.getvalue(), content_type='application/pdf')
        else:
            return HttpResponse("Error Rendering PDF", status=400)


class Render2:
    @staticmethod
    def render(path: str, params: dict):
        template = get_template('deed/purchase_deed_download_form.html')
        html = template.render(params)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            return HttpResponse(response.getvalue(), content_type='application/pdf')
        else:
            return HttpResponse("Error Rendering PDF", status=400)


def select_deed(request):
    return render(request, 'deed/select_deed.html', )


def sales_deed(request):
    form = SalesDeedForm()
    form2 = SalesDeedRepresentativeForm()
    if request.method == 'POST':
        form = SalesDeedForm(request.POST)
        form2 = SalesDeedRepresentativeForm(request.POST)
        if form.is_valid() and form2.is_valid():
            unique_id = str(uuid4())
            formm = form.save(commit=False)
            formm.unique_id = unique_id
            formm.save()

            formm2 = form2.save(commit=False)
            formm2.representative_unique_id = unique_id
            formm2.save()
            return redirect('form-download-sales', unique_id=unique_id)
    return render(request, 'deed/sales_deed.html', {'form': form, 'form2': form2})


def load_fwm(request):
    gender_id = request.GET.get('gender_id')
    fwm = FMW.objects.filter(gender_id=gender_id)
    return render(request, 'deed/fwm_dropdown_list_options.html', {'fwm': fwm})


def load_fwm2(request):
    gender_id = request.GET.get('gender_id2')
    fwm = FMW.objects.filter(gender_id=gender_id)
    return render(request, 'deed/fwm_dropdown_list_options2.html', {'fwm': fwm})


def gift_deed(request):
    form = GiftDeedForm()
    form2 = GiftDonorDeedForm()
    if request.method == 'POST':
        form = GiftDeedForm(request.POST)
        form2 = GiftDonorDeedForm(request.POST)
        if form.is_valid() and form2.is_valid():
            unique_id = str(uuid4())
            formm = form.save(commit=False)
            formm.unique_id = unique_id
            formm.save()

            formm2 = form2.save(commit=False)
            formm2.representative_unique_id = unique_id
            formm2.save()
            return redirect('form-download-gift', unique_id=unique_id)
    return render(request, 'deed/gift_deed.html', {'form': form, 'form2': form2})


def load_gift(request):
    gender_id = request.GET.get('gender_id')
    fwm = FMW.objects.filter(gender_id=gender_id)
    return render(request, 'deed/gift_dropdown_list_options.html', {'fwm': fwm})


def load_gift2(request):
    gender_id = request.GET.get('gender_id2')
    fwm = FMW.objects.filter(gender_id=gender_id)
    return render(request, 'deed/gift_dropdown_list_options2.html', {'fwm': fwm})


def purchase_deed(request):
    form = PurchaseDeedForm()
    if request.method == 'POST':
        form = PurchaseDeedForm(request.POST)
        if form.is_valid():
            unique_id = str(uuid4())
            formm = form.save(commit=False)
            formm.unique_id = unique_id
            formm.save()
            return redirect('form-download-purchase', unique_id=unique_id)
    return render(request, 'deed/purchase_deed.html', {'form': form})


def download_form_purchase(request, unique_id):
    sale_deed = PurchaseDeed.objects.get(unique_id=unique_id)
    now = datetime.now()  # current date and time
    year = now.strftime("%Y")
    month = now.strftime("%b")
    day = now.strftime("%d")
    context = {
        'deed': sale_deed,
        'year': year,
        'month': month,
        'day': day,
    }
    return Render2.render('deed/purchase_deed_download_form.html', context)


def download_form_sales(request, unique_id):
    sale_deed = SalesDeed.objects.get(unique_id=unique_id)
    sales_deed_representative = SalesDeedRepresentative.objects.get(representative_unique_id=unique_id)

    now = datetime.now()  # current date and time
    year = now.strftime("%Y")
    month = now.strftime("%b")
    day = now.strftime("%d")

    sale_deed_age = int(year) - int(sale_deed.birth_date.strftime("%Y"))
    sales_deed_representative_age = int(year) - int(sales_deed_representative.representative_birth_date.strftime("%Y"))
    context = {
        'sale_deed': sale_deed,
        'sale_deed_age': sale_deed_age,
        'sales_deed_representative': sales_deed_representative,
        'sales_deed_representative_age': sales_deed_representative_age,
        'year': year,
        'month': month,
        'day': day,
    }
    # form = DeedEditDownloadForm()
    # if request.method == 'POST':
    #     form = DeedEditDownloadForm(request.POST)
    #     if form.is_valid():
    #         formm = form.save(commit=False)
    #         formm.name = 'sales_deed'
    #         formm.save()
    return Render.render('deed/sales_deed_download_form.html', context)


def download_form_gift(request, unique_id):
    sale_deed = GiftDeed.objects.get(unique_id=unique_id)
    sales_deed_representative = GiftDonorDeed.objects.get(representative_unique_id=unique_id)

    now = datetime.now()  # current date and time
    year = now.strftime("%Y")
    month = now.strftime("%b")
    day = now.strftime("%d")

    sale_deed_age = int(year) - int(sale_deed.birth_date.strftime("%Y"))
    sales_deed_representative_age = int(year) - int(sales_deed_representative.representative_birth_date.strftime("%Y"))
    context = {
        'sale_deed': sale_deed,
        'sale_deed_age': sale_deed_age,
        'sales_deed_representative': sales_deed_representative,
        'sales_deed_representative_age': sales_deed_representative_age,
        'year': year,
        'month': month,
        'day': day,
    }
    return Render1.render('deed/gift_deed_download_form.html', context)

#
# def deed_edit_download(request):
#     form = DeedEditDownloadForm()
#     if request.method == 'POST':
#         form = DeedEditDownloadForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('select-deed')
#     return render(request, 'deed/form1.html', {'form': form})


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'deed/form1.html', {'form': form})


def person_create_view2(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'deed/form2.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'deed/form1.html', {'form': form})


# AJAX
def load_cities(request):
    country_id = request.GET.get('gender_id')
    cities = Position.objects.filter(gender_id=country_id).all()
    return render(request, 'deed/city_dropdown_list_options.html', {'cities': cities})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def load_income(request):
    position_id = request.GET.get('position_id')
    pos = Position.objects.get(id=position_id)
    if pos.earning == "YES":
        data = 'show'
        return render(request, 'deed/income_dropdown_list_options.html', {'data': data})
    else:
        data = 'hide'
        return render(request, 'deed/income_dropdown_list_options.html', {'data': data})


shops/deed/templates/deed/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

shops/deed/templates/deed/form1.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Form1</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <title>Form1</title>
</head>

<body style="margin:2em;">
<h2>Person Form</h2>

<form method="post" id="personForm" class='incomeForm' data-cities-url="{% url 'ajax_load_cities' %}" data-income-url="{% url 'ajax_load_income' %}">
  {% csrf_token %}
  <table>
    <tr>
      <th>
        <label class="form-label" for="id_name">Name:</label>
      </th>
      <td>
        <input class="form-control" type="text" name="name" maxlength="124" required id="id_name">
      </td>
    </tr>

    <tr>
      <th>
        <label class="form-label" for="id_gender">Gender:</label>
      </th>
      <td>
        <select class="form-control" name="gender" id="id_gender">
          <option value="" selected>---------</option>
          <option value="1">Male</option>
          <option value="2">Female</option>
        </select>
      </td>
    </tr>

    <tr>
      <th>
        <label class="form-label" for="id_position">Position:</label>
      </th>
      <td>
        <select class="form-control" name="position" id="id_position">
          <option value="" selected>---------</option>
        </select>
      </td>
    </tr>

    <tr id='income' style="display:none;">
      <th>
        <label for="id_income" class="form-label" >Income(Rs):</label>
      </th>
      <td>
        <input class="form-control" type="number" name="income" step="any" id="id_income">
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_married" class="form-label" >Marital Status: &nbsp;</label>
      </th>
      <td>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="married" id="id_married">
          <label class="form-check-label" for="id_married">
            Married
          </label>
        </div>
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_birth_date" class="form-label" >Birth Date:</label>
      </th>
      <td>
        <input class="form-control" type="date" name="birth_date" id="id_birth_date"  max=''>
      </td>
    </tr>

  </table>

  <br>
  <input style="margin-left:5em;" class="btn btn-outline-info" type="submit" value="Submit">

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_gender").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view

        const genderId = $(this).val();  // get the selected gender ID from the HTML input
        $("#income").hide();
        $("#id_income").val('');
        $("#id_position").html('<option value="">---------</option>');


        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'gender_id': genderId       // add the gender id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_position").html(data);  // replace the contents of the position input with the data that came from the server
                data
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (position) {
                    html_data += `<option value="${position.id}">${position.name}</option>`
                });
                console.log(html_data);
                $("#id_position").html(html_data);

                */
            }
        });

    });

     $("#id_position").change(function () {
        const url2 = $(".incomeForm").attr("data-income-url");
        $("#income").hide();
        $("#id_income").val('');
        const positionId = $(this).val();

        $.ajax({
            url: url2,
            data: {
                'position_id': positionId
            },
            success: function (data) {
                console.log(data);
                $("#id_income").html(data);
                if (data == 'show'){
                    $("#income").show();
                }
                else {
                    $("#income").hide();
                }
            }
        });
    });

     $(function(){
    var dtToday = new Date();

    var month = dtToday.getMonth() + 1;
    var day = dtToday.getDate();
    var year = dtToday.getFullYear() - 18 ;

    if(month < 10)
        month = '0' + month.toString();
    if(day < 10)
        day = '0' + day.toString();

    var maxDate = year + '-' + month + '-' + day;
    $('#id_birth_date').attr('max', maxDate);
});
</script>

</body>
</html>

shops/deed/templates/deed/fwm_dropdown_list_options.html
<option value="">---------</option>
{% for g in fwm %}
<option value="{{ g.pk }}">{{ g.name }}</option>
{% endfor %}

shops/deed/templates/deed/gift_dropdown_list_options.html
<option value="">---------</option>
{% for g in fwm %}
<option value="{{ g.pk }}">{{ g.name }}</option>
{% endfor %}

shops/deed/templates/deed/gift_dropdown_list_options2.html
<option value="">---------</option>
{% for g in fwm %}
<option value="{{ g.pk }}">{{ g.name }}</option>
{% endfor %}

shops/deed/templates/deed/sales_deed.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <title>Sales Deed</title>
</head>
<body>
<h2>Sales Deed</h2>

<form method="post" class='Fwm Fwm2' data-fwm-url="{% url 'ajax-fwm-url' %}" data-fwm-url2="{% url 'ajax-fwm-url2' %}">
  {% csrf_token %}
  <table>
    <tr>
      <th>
        <label class="form-label" for="id_name">Name:</label>
      </th>
      <td>
        <input class="form-control" type="text" name="name" maxlength="124" required id="id_name">
      </td>
    </tr>

     <tr>
      <th>
        <label class="form-label" for="id_gender">Gender:</label>
      </th>
      <td>
        <select class="form-control" name="gender" id="id_gender" required>
          <option value="" selected>---------</option>
          <option value="1">Male</option>
          <option value="2">Female</option>
        </select>
      </td>
    </tr>

    <tr id='rel' style="display:none;">
      <th>
        <label style="display:none;" class="form-label" for="id_fwm"></label>
        <select class="form-control" name="fwm" id="id_fwm" required>
          <option value="" selected>---------</option>
        </select>
      </th>
      <td>
        <input class="form-control" type="text" name="fwm_name" id="id_fwm_name" required>
      </td>
    </tr>

     <tr>
      <th>
        <label for="id_married" class="form-label" >Marital Status: &nbsp;</label>
      </th>
      <td>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="married" id="id_married">
          <label class="form-check-label" for="id_married">
            Married
          </label>
        </div>
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_address" class="form-label" >Address:</label>
      </th>
      <td>
        <textarea class="form-control" name="address" id="id_address" rows="2" cols="50" required></textarea>
      </td>
    </tr>

    <tr>
      <th>
        <label class="form-label" for="id_occupation">Occupation:</label>
      </th>
      <td>
        <input class="form-control" name="occupation" type=text id="id_occupation" required>
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_birth_date" class="form-label">Birth Date:</label>
      </th>
      <td>
        <input class="form-control" type="date" name="birth_date" id="id_birth_date"  max='' required>
      </td>
    </tr>

    <tr>
      <th>
        <label class="form-label" for="id_representy">Representy:</label>
      </th>
      <td>
        <select class="form-control" name="representy" required id="id_representy">
          <option value="" selected>---------</option>
          <option value="Agent">Agent</option>
          <option value="Father">Father</option>
          <option value="Mother">Mother</option>
          <option value="Brother">Brother</option>
          <option value="Guardian">Guardian</option>
          </select>
      </td>
    </tr>


  </table>
  <br>
  <br>
  <br>
  <table>
    <tr>
      <th>
        <label class="form-label" for="id_representative_name">Name:</label>
      </th>
      <td>
        <input class="form-control" type="text" name="representative_name" maxlength="124" required id="id_representative_name">
      </td>
    </tr>

     <tr>
      <th>
        <label class="form-label" for="id_representative_gender">Gender:</label>
      </th>
      <td>
        <select class="form-control" name="representative_gender" id="id_representative_gender" required>
          <option value="" selected>---------</option>
          <option value="1">Male</option>
          <option value="2">Female</option>
        </select>
      </td>
    </tr>

<!--    <tr style="display:none;">-->
<!--       <th>-->
<!--        <label class="form-label" for="id_representative_fwm"></label>-->
<!--      </th>-->
<!--      <td>-->
<!--        <input class="form-control" name="representative_fwm_name" type=text id="id_representative_fwm" required>-->
<!--      </td>-->
<!--    </tr>-->

    <tr id='rel2' style="display:none;">
      <th>
        <label style="display:none;" class="form-label" for="id_representative_fwm"></label>
        <select class="form-control" name="representative_fwm" id="id_representative_fwm" required>
          <option value="" selected>---------</option>
        </select>
<!--        <label class="form-label" for="id_representative_fwm_name" id="rel3"></label>-->
      </th>
      <td>
        <input class="form-control" name="representative_fwm_name" type=text id="id_representative_fwm_name" required>
      </td>
    </tr>

     <tr>
      <th>
        <label for="id_representative_married" class="form-label" >Marital Status: &nbsp;</label>
      </th>
      <td>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name=representative_"married" id="id_representative_married">
          <label class="form-check-label" for="id_representative_married">
            Married
          </label>
        </div>
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_representative_address" class="form-label" >Address:</label>
      </th>
      <td>
        <textarea class="form-control" name="representative_address" id="id_representative_address" rows="2" cols="50" required></textarea>
      </td>
    </tr>

    <tr>
      <th>
        <label class="form-label" for="id_representative_occupation">Occupation:</label>
      </th>
      <td>
        <input class="form-control" name="representative_occupation" type=text id="id_representative_occupation" required>
      </td>
    </tr>

    <tr>
      <th>
        <label for="id_representative_birth_date" class="form-label">Birth Date:</label>
      </th>
      <td>
        <input class="form-control" type="date" name="representative_birth_date" id="id_representative_birth_date"  max='' required >
      </td>
    </tr>
  </table>

  <br>
  <input style="margin-left:5em;" class="btn btn-outline-info" type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
     $("#id_gender").change(function () {
        const url = $(".Fwm").attr("data-fwm-url");
        const fwm = $(this).val();
        $("#rel").hide();
        $('#id_fwm').val('');
        $("#id_fwm_name").val('');


        $.ajax({
            url: url,
            data: {
                'gender_id': fwm
            },
            success: function (data) {
                console.log(data);
                $('#id_fwm').html(data);
                $('#id_fwm').val(data);
                $("#rel").show();

            }
        });
    });


<!--    $("#rel1").change(function () {-->
<!--        $('#id_fwm').val('');-->
<!--        $('#id_fwm').val($('#rel1').val());-->
<!--    });-->


    $("#id_representative_gender").change(function () {
        const url2 = $(".Fwm2").attr("data-fwm-url2");
        const fwm2 = $(this).val();
        $("#rel2").hide();
        $('#id_representative_fwm').val('');
        $("#id_representative_fwm_name").val('');


        $.ajax({
            url: url2,
            data: {
                'gender_id2': fwm2
            },
            success: function (data) {
                console.log(data);
                $('#id_representative_fwm').html(data);
                $('#id_representative_fwm').val(data);
                $("#rel2").show();
            }
        });
    });


<!--     $("#rel3").change(function () {-->
<!--        $('#id_representative_fwm').val('');-->
<!--        $('#id_representative_fwm').val($('#rel3').val());-->
<!--    });-->


     $(function(){
    var dtToday = new Date();

    var month = dtToday.getMonth();
    var day = dtToday.getDate();
    var year = dtToday.getFullYear()  ;
    month = month + 1
    year = year - 18
    if(month < 10)
        month = '0' + month.toString();
    if(day < 10)
        day = '0' + day.toString();

    var maxDate = year + '-' + month + '-' + day;
    $('#id_birth_date').attr('max', maxDate);
    $('#id_representative_birth_date').attr('max', maxDate);
});
</script>

</body>
</html>